### ISSUE TITLE
Fix or hide some entry points to localization framework to avoid inconsistency

### ISSUE THREAD

**Issue by minarja** [Scalesoft/localization#3]
When you use ILocalization and Translator, you can get translation in different languages. This behavior can make application inconsistent.

Sample:
ILocalization localization = getLocalization();
var translatedA = localization.Translate("key", "scope"));
var translatedB = Translator.Translate("key", null, "scope"));

Now you can get two different result (translatedA  != translatedB)

**Comment by trejjam** [comment]
Can you prepare a failing test in `feature/dynamic-module-configuration` or [feature/nhibernate](https://github.com/Scalesoft/localization/tree/feature/nhibernate)?

**Comment by minarja** [comment]
Class [Translator](https://github.com/Scalesoft/localization/blob/master/Solution/Localization.CoreLibrary/Translator/Translator.cs) was deleted in [feature/nhibernate](https://github.com/Scalesoft/localization/tree/feature/nhibernate). This fixed issue and use case can not be reproduced
